//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banca
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {

        public int user_Id { get; set; }
        public string user_Cedula { get; set; }
        public string user_Nombre { get; set; }
        public string user_Direccion { get; set; }
        public Nullable<System.DateTime> user_FechaNacimiento { get; set; }
        public string user_Email { get; set; }
        public Nullable<int> user_Edad { get; set; }

        
    }
}
